### PR TITLE
(chore) free memory using asn1_time_free when asn1_time_set is used

### PR DESCRIPTION
**Pull request by vinayakhulawale**
For consistency using time_free instead of string_free

### CODE REVIEW

**Comment by fffonion** [comment]
@vinayakhulawale types like ASN1_*TIME and ASN1_INTEGER are actually all stored as ASN.1 encoded string (ASN1_STRING), the types basically control different routines when parsing. For example if you want to parse the string into a integer, you pass in an ASN1_INTEGER and expect a integer to return. In fact the openssl manaul also suggests using ASN1_STRING_free on those types.
My thought will be if we want to go with this path, we should use this pattern everywhere for consistency. Considering we will likely consult openssl manual in the future, I would doubt if there's a good path to pursue 
Regarding free there's no difference in each variants.

**Comment by vinayakhulawale** [comment]
@fffonion - yep, manual does say we can use `ASN1_STRING_free` to free memory for `ASN1_TIME` structure but I feel it would be more consistent to use `ASN1_TIME_free` when we explicitly use `ASN1_TIME*` .  

I was checking openssl tests, they use both approaches ([time_free](https://github.com/openssl/openssl/blob/master/test/asn1_time_test.c#L176) and [string_free](https://github.com/openssl/openssl/blob/master/test/asn1_time_test.c#L376-L378)),  Libraries like luaossl sticks to [time_free](https://github.com/wahern/luaossl/blob/master/src/openssl.c#L8116-L8134)

**Comment by vinayakhulawale** [comment]
I am OK to close this PR, if you want to use string_free. Also if you are OK with time_free usage - I can modify script and other occurrences too.

**Comment by vinayakhulawale** [comment]
@fffonion -  did you get chance to decide if you want to go with `time_free` or stick to `string_free` ?

**Pull request closed without merging**
